module.exports = {
  // for socket & redux
  START_GAME : 'START_GAME',
  NEW_MESSAGE : 'NEW_MESSAGE',
  // only redux
  SHOW_GESTURE : 'SHOW_GESTURE',
  SHOW_LOADER : 'SHOW_LOADER',
  RESET : 'RESET',
  MAKE_A_CHOICE : 'MAKE_A_CHOICE',
  // only socket events
  READY : 'READY',
  EXIT : 'EXIT',
  RESULT : 'RESULT',
  GESTURE : 'GESTURE',
  PLAY_INVITATION : 'PLAY_INVITATION',
  INVITATION_DISAGREE : 'INVITATION_DISAGREE',
  INVITATION_AGREE : 'INVITATION_AGREE',
  OPPONENT_LEAVE : 'OPPONENT_LEAVE',
}
